### ISSUE TITLE
Assert error (GDI gui handle leak?)

### ISSUE THREAD

**Issue by sixtenbe** [sixtenbe/ping-graph-tool#4]
The program sometimes throws an assert error, which originates from matplotlib in some way I think. Essentially from some googling I did on this problem at one time, said it was a problem with GUI handles leaking, which I thought I fixed by force removing the line objects from the canvas when stopping.

Luckily this error doesn't stop the execution of the program, it just throws up a msgbox when the error is captured and I've only encountered the bug when running a fullscreen program (a game) and the program has been running for at least a few hours, actively plotting.

In the end I currently think this is somehow related to how I do the .blit in matplotlib to reduce CPU strain. It might be that a different call should be used than .blit(ax.bbox) to update the canvas, but the commands that I've found when googling doesn't seem to exist when I try them. A method I've seen in some guides about using blit called for using canvas.Update() to draw without encountering any leaks with the wx-backend, but that command doesn't seem to exist.

**Comment by sixtenbe** [comment]
Example traceback for the error

`Uncaught exception:
Traceback (most recent call last):
  File "I:\Dropbox\ping\ping_gui.pyw", line 479, in run_with_except_hook
    run_old(*args, **kw)
  File "C:\Python27\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "I:\Dropbox\ping\ping_gui.pyw", line 239, in ping_it
    line_timeout])
  File "I:\Dropbox\ping\wxplot.py", line 803, in update_plot_only
    self.canvas.blit(ax.bbox)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 71, in blit
    destDC.SelectObject(self.bitmap)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_gdi.py", line 4872, in SelectObject
    return _gdi_.MemoryDC_SelectObject(*args, **kwargs)
PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\dcmemory.cpp(118) in wxMemoryDC::DoSelect(): Couldn't select a bitmap into wxMemoryDC`

Likely a result of thread unsafe handling,
