### ISSUE TITLE
wxYield called recrsively

### ISSUE THREAD

**Issue by sixtenbe** [sixtenbe/ping-graph-tool#6]
```
Uncaught exception:
Traceback (most recent call last):
  File "I:\Dropbox\ping\ping_gui.pyw", line 246, in onPlotting
    self.line_ping, self.line_timeout]
  File "I:\Dropbox\ping\wxplot.py", line 822, in update_plot_only
    self.canvas.flush_events()
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_wx.py", line 758, in flush_events
    wx.Yield()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7698, in Yield
    return _core_.Yield(*args)
PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\app.cpp(707) in wxApp::Yield(): wxYield called recursively
```
Following error will occur at random intervals, but usually it seems to be a few days in between.

**Comment by sixtenbe** [comment]
calling flush_events has been disabled for the moment, which appears to have fixed it.
